[package]
name = "wasm"
version = "0.1.0"
authors = ["sebcrozet <developer@crozet.re>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.18"
kiss3d = { path = "../..", features = [ "conrod" ] }
rand = { version = "0.6" }
wasm-bindgen = "0.2"